import type {
  Curriculum,
  CurriculumVersion,
  Grade,
  LearningOutcome,
  SkillSummary,
} from '../types/curriculum.types'

export const MOCK_CURRICULUM: Curriculum = {
  id: 'curr-moet-gdpt',
  curriculum_code: 'MOET-GDPT-2018',
  name_en: 'General Education Curriculum 2018 — English',
  name_vi: 'Chương trình Giáo dục phổ thông 2018 — Môn Tiếng Anh',
  authority_name: 'Ministry of Education and Training (Bộ GD&ĐT)',
  status: 'ACTIVE',
}

export const MOCK_VERSIONS: CurriculumVersion[] = [
  {
    id: 'ver-2018-v1',
    curriculum_id: 'curr-moet-gdpt',
    source_version_id: 'SRC-MOET-GDPT-2018',
    version_label: 'v1.0 (TT 32/2018/TT-BGDĐT)',
    document_reference: 'Thông tư 32/2018/TT-BGDĐT',
    effective_from: '2019-02-15',
    effective_to: '2022-08-02',
    status: 'DEPRECATED',
    supersedes_version_id: null,
    amends_source_id: null,
    change_reason: 'Statutory baseline enactment',
    reviewed_by: 'Council of National Curriculum Review',
    reviewed_at: '2018-12-26T00:00:00Z',
    approved_by: 'Minister of Education',
    approved_at: '2018-12-26T00:00:00Z',
    created_at: '2019-01-01T00:00:00Z',
    updated_at: '2022-08-03T00:00:00Z',
  },
  {
    id: 'ver-2022-v2',
    curriculum_id: 'curr-moet-gdpt',
    source_version_id: 'SRC-MOET-GDPT-AMEND-2022-13',
    version_label: 'v2.0 (TT 13/2022/TT-BGDĐT)',
    document_reference: 'Thông tư 13/2022/TT-BGDĐT sửa đổi TT 32/2018',
    effective_from: '2022-08-03',
    effective_to: null,
    status: 'APPROVED',
    supersedes_version_id: 'ver-2018-v1',
    amends_source_id: 'SRC-MOET-GDPT-2018',
    change_reason:
      'Điều chỉnh phân phối môn học và cập nhật chuẩn yêu cầu cần đạt cấp THCS/THPT',
    reviewed_by: 'MOET Curriculum Commission',
    reviewed_at: '2022-08-01T08:00:00Z',
    approved_by: 'Minister of Education',
    approved_at: '2022-08-03T08:00:00Z',
    created_at: '2022-08-03T00:00:00Z',
    updated_at: '2026-08-27T00:00:00Z',
  },
  {
    id: 'ver-2026-draft',
    curriculum_id: 'curr-moet-gdpt',
    source_version_id: 'SRC-MOET-GDPT-DRAFT-2026',
    version_label: 'v2.1-Draft (Rà soát khung kỹ năng số 2026)',
    document_reference: 'Dự thảo hướng dẫn thực hiện nhiệm vụ năm học',
    effective_from: '2026-09-01',
    effective_to: null,
    status: 'DRAFT',
    supersedes_version_id: 'ver-2022-v2',
    amends_source_id: 'SRC-MOET-GDPT-AMEND-2022-13',
    change_reason:
      'Bổ sung liên kết đánh giá năng lực thực tế & bám sát chuẩn SGK mới',
    reviewed_by: null,
    reviewed_at: null,
    approved_by: null,
    approved_at: null,
    created_at: '2026-09-01T00:00:00Z',
    updated_at: '2026-09-04T00:00:00Z',
  },
]

export const MOCK_GRADES: Grade[] = [
  {
    id: 'grade-6',
    curriculum_version_id: 'ver-2022-v2',
    grade_code: 'G6',
    display_order: 1,
    name_en: 'Grade 6',
    name_vi: 'Lớp 6',
  },
  {
    id: 'grade-7',
    curriculum_version_id: 'ver-2022-v2',
    grade_code: 'G7',
    display_order: 2,
    name_en: 'Grade 7',
    name_vi: 'Lớp 7',
  },
  {
    id: 'grade-8',
    curriculum_version_id: 'ver-2022-v2',
    grade_code: 'G8',
    display_order: 3,
    name_en: 'Grade 8',
    name_vi: 'Lớp 8',
  },
  {
    id: 'grade-9',
    curriculum_version_id: 'ver-2022-v2',
    grade_code: 'G9',
    display_order: 4,
    name_en: 'Grade 9',
    name_vi: 'Lớp 9',
  },
]

export const MOCK_SKILLS: SkillSummary[] = [
  {
    id: 'skl-gram-pres-simple',
    skill_code: 'SKL-GRM-001',
    name_en: 'Present Simple Tense for Daily Routines',
    name_vi: 'Thì Hiện tại đơn diễn tả thói quen hằng ngày',
    domain: 'GRAMMAR',
    cefr_reference_band: 'A1-A2',
  },
  {
    id: 'skl-gram-past-simple',
    skill_code: 'SKL-GRM-002',
    name_en: 'Past Simple with Regular and Irregular Verbs',
    name_vi: 'Thì Quá khứ đơn với động từ có quy tắc và bất quy tắc',
    domain: 'GRAMMAR',
    cefr_reference_band: 'A2',
  },
  {
    id: 'skl-voc-school-env',
    skill_code: 'SKL-VOC-010',
    name_en: 'School Objects and Learning Activities Vocabulary',
    name_vi: 'Từ vựng đồ dùng học tập và hoạt động ở trường',
    domain: 'VOCABULARY',
    cefr_reference_band: 'A1',
  },
  {
    id: 'skl-lis-gist-dialog',
    skill_code: 'SKL-LIS-005',
    name_en: 'Listening for Main Idea in Short Everyday Dialogues',
    name_vi: 'Nghe hiểu ý chính trong đoạn hội thoại hằng ngày ngắn',
    domain: 'LISTENING',
    cefr_reference_band: 'A2',
  },
  {
    id: 'skl-rea-detail-notices',
    skill_code: 'SKL-REA-008',
    name_en: 'Reading for Specific Information in Notices and Signs',
    name_vi: 'Đọc quét thông tin chi tiết trong thông báo và biển hiệu',
    domain: 'READING',
    cefr_reference_band: 'A2',
  },
  {
    id: 'skl-spk-self-intro',
    skill_code: 'SKL-SPK-003',
    name_en: 'Self-introduction: Personal Information, Hobbies & Family',
    name_vi: 'Tự giới thiệu bản thân: Thông tin cá nhân, sở thích & gia đình',
    domain: 'SPEAKING',
    cefr_reference_band: 'A1-A2',
  },
  {
    id: 'skl-wri-short-email',
    skill_code: 'SKL-WRI-004',
    name_en: 'Writing a Short Email / Note about Weekend Plans',
    name_vi: 'Viết email / ghi chú ngắn về kế hoạch cuối tuần',
    domain: 'WRITING',
    cefr_reference_band: 'A2',
  },
]

export const MOCK_OUTCOMES_BY_GRADE: Record<string, LearningOutcome[]> = {
  'grade-6': [
    {
      id: 'out-g6-001',
      curriculum_version_id: 'ver-2022-v2',
      grade_id: 'grade-6',
      outcome_code: 'MOET-G6-L01',
      statement_en:
        'Listen and identify key details in short monologues/dialogues related to school and personal life.',
      statement_vi:
        'Nghe và xác định được thông tin chi tiết trong các đoạn độc thoại/hội thoại ngắn về chủ đề trường học và đời sống cá nhân.',
      source_locator:
        'Chương trình GDPT Tiếng Anh, Mục 4.2 - Lớp 6, Kỹ năng Nghe',
      status: 'APPROVED',
      mappings: [
        {
          id: 'map-001',
          learning_outcome_id: 'out-g6-001',
          skill_id: 'skl-lis-gist-dialog',
          mapping_role: 'PRIMARY_TARGET',
          importance: 'REQUIRED',
          confidence: 0.95,
          mapping_version: 'v1.0',
          status: 'APPROVED',
          verified_by: 'Academic Lead',
          verified_at: '2022-08-10T09:00:00Z',
          skill: MOCK_SKILLS[3],
        },
      ],
    },
    {
      id: 'out-g6-002',
      curriculum_version_id: 'ver-2022-v2',
      grade_id: 'grade-6',
      outcome_code: 'MOET-G6-S01',
      statement_en:
        'Introduce self, family members and describe simple daily routines using present simple.',
      statement_vi:
        'Tự giới thiệu bản thân, các thành viên trong gia đình và mô tả thói quen hằng ngày đơn giản sử dụng thì hiện tại đơn.',
      source_locator:
        'Chương trình GDPT Tiếng Anh, Mục 4.2 - Lớp 6, Kỹ năng Nói',
      status: 'APPROVED',
      mappings: [
        {
          id: 'map-002',
          learning_outcome_id: 'out-g6-002',
          skill_id: 'skl-spk-self-intro',
          mapping_role: 'PRIMARY_TARGET',
          importance: 'REQUIRED',
          confidence: 0.98,
          mapping_version: 'v1.0',
          status: 'APPROVED',
          verified_by: 'Academic Lead',
          verified_at: '2022-08-10T09:00:00Z',
          skill: MOCK_SKILLS[5],
        },
        {
          id: 'map-003',
          learning_outcome_id: 'out-g6-002',
          skill_id: 'skl-gram-pres-simple',
          mapping_role: 'SECONDARY_TARGET',
          importance: 'CORE',
          confidence: 0.9,
          mapping_version: 'v1.0',
          status: 'APPROVED',
          verified_by: 'Academic Lead',
          verified_at: '2022-08-10T09:00:00Z',
          skill: MOCK_SKILLS[0],
        },
      ],
    },
    {
      id: 'out-g6-003',
      curriculum_version_id: 'ver-2022-v2',
      grade_id: 'grade-6',
      outcome_code: 'MOET-G6-R01',
      statement_en:
        'Read and comprehend simple informational texts (posters, emails, timetables) of about 100-120 words.',
      statement_vi:
        'Đọc hiểu các văn bản thông tin ngắn gọn (áp phích, email, thời khóa biểu) độ dài khoảng 100-120 từ.',
      source_locator:
        'Chương trình GDPT Tiếng Anh, Mục 4.2 - Lớp 6, Kỹ năng Đọc',
      status: 'APPROVED',
      mappings: [
        {
          id: 'map-004',
          learning_outcome_id: 'out-g6-003',
          skill_id: 'skl-rea-detail-notices',
          mapping_role: 'PRIMARY_TARGET',
          importance: 'REQUIRED',
          confidence: 0.92,
          mapping_version: 'v1.0',
          status: 'APPROVED',
          verified_by: 'Academic Lead',
          verified_at: '2022-08-10T09:00:00Z',
          skill: MOCK_SKILLS[4],
        },
      ],
    },
  ],
  'grade-7': [
    {
      id: 'out-g7-001',
      curriculum_version_id: 'ver-2022-v2',
      grade_id: 'grade-7',
      outcome_code: 'MOET-G7-W01',
      statement_en:
        'Write a short passage (50-60 words) describing a past holiday, community activity or favorite hobby.',
      statement_vi:
        'Viết một đoạn văn ngắn (50-60 từ) kể lại chuyến đi chơi trong quá khứ, hoạt động cộng đồng hoặc sở thích cá nhân.',
      source_locator:
        'Chương trình GDPT Tiếng Anh, Mục 4.2 - Lớp 7, Kỹ năng Viết',
      status: 'APPROVED',
      mappings: [
        {
          id: 'map-005',
          learning_outcome_id: 'out-g7-001',
          skill_id: 'skl-gram-past-simple',
          mapping_role: 'PRIMARY_TARGET',
          importance: 'REQUIRED',
          confidence: 0.96,
          mapping_version: 'v1.0',
          status: 'APPROVED',
          verified_by: 'Academic Lead',
          verified_at: '2022-08-10T09:00:00Z',
          skill: MOCK_SKILLS[1],
        },
        {
          id: 'map-006',
          learning_outcome_id: 'out-g7-001',
          skill_id: 'skl-wri-short-email',
          mapping_role: 'SECONDARY_TARGET',
          importance: 'SUPPORTING',
          confidence: 0.85,
          mapping_version: 'v1.0',
          status: 'APPROVED',
          verified_by: 'Academic Lead',
          verified_at: '2022-08-10T09:00:00Z',
          skill: MOCK_SKILLS[6],
        },
      ],
    },
  ],
}
